week5/w5d1-testing/RedditClone-unfinished/Reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :sessions

  resources :subs do
    resources :posts, only: [:new, :edit, :create, :update, :show, :destroy]
  end
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :url, :content, presence: true

  belongs_to :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User


end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, presence: true
  validates :moderator, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :posts
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bc_obj = BCrypt::Password.new(password_digest)
    bc_obj.is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(128)
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(128)
  end

end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_login

  def login(user)
    session[:session_token] = user.session_token
    user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
    @current_user
  end

  def logout
    return if current_user.nil?
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    unless logged_in?
      flash[:errors] = ["You have to be logged_in to do that"]
      redirect_to new_sessions_url
    end
  end

end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_login

  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
    render 'new'
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      render :show
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def show
    @post = Post.find_by(id: params[:id])
    render 'show'
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    sub_id = params[:sub_id]
    @post.destroy
    redirect_to sub_url(sub_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, :user_id)
  end

end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render 'new'
  end

  def create
    @user = User.find_by_credentials(
      session_params[:username],
      session_params[:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["invalid credentials!"]
      render 'new'
    end
  end

  def destroy
    logout
    current_user.reset_session_token!
    redirect_to new_sessions_url
  end


  private

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def index
    @subs = Sub.all
    render 'index'
  end

  def new
    render 'new'
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      render :show
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update_attributes(sub_params)
      render :show
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end

  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render 'show'
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    render :index
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :user_id)
  end


end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/helpers/users_helper.rb
module UsersHelper
end

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


  <% if logged_in? %>
    <%= "Hello, #{current_user.username}!" %>
    <%= link_to "Sign Out", sessions_url, method: :delete %>
  <% else %>
    <%= link_to "Log In", new_sessions_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>
  <br><br>
  <% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
    <%= error %>
    <% end %>
  <% end %>

  <%= yield %>

</body>
</html>

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/posts/_form.html.erb
<% action = ( post.id ? sub_post_url(post.sub_id, post.id) : sub_posts_url(post.sub_id) ) %>
<% method = ( post.id ? "patch" : "post" ) %>


<form action= '<%=action%>', method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label><br>
  <input type="text" name="post[title]" value='<%= post.id ? "#{post.title}" : "" %>'><br><br>

  <label for="title">URL</label><br>
  <input type="text" name="post[url]" value='<%= post.id ? "#{post.url}" : "" %>'><br><br>

  <label for="description">Content</label><br>
  <input type="text" name="post[content]" value='<%= post.id ? "#{post.content}" : "" %>'><br><br>

  <input type="submit" value="<%= post.id ? "Save #{post.title}" : "Create Post" %>">


</form>

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/posts/edit.html.erb
<h1>Edit your post</h1>
<%= render 'form', post: @post %>

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/posts/new.html.erb
<h1>Create a post</h1>
<%= render 'form', post: @post %>

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  URL: <a href='<%= @post.url if @post.url %>'><%=@post.url%></a>
</p>

<p>
  Content: <%= @post.content if @post.content %>
</p>
<p>
  Author: <%= @post.author.username %>
</p>

<% if current_user.id == @post.user_id %>
  <%= link_to "Edit Post", edit_sub_post_url(@post.sub_id, @post.id) %>
  <%= link_to "Delete Post", sub_post_url(@post.sub_id, @post.id), method: :delete %>
<% end %>

week5/w5d1-testing/RedditClone-unfinished/Reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="username">Username</label><br>
  <input type="text" name="user[username]"><br>

  <label for="password">Password</label><br>
  <input type="password" name="user[password]"><br>

  <input type="submit" value="Sign Up">
</form>